# Generated by Django 5.0.2 on 2024-09-05 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Participant',
            new_name='Member',
        ),
    ]
