# Generated by Django 5.0.2 on 2024-10-11 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='expo',
            field=models.IntegerField(choices=[(1, 'Banks&Business'), (2, 'UzCharmEURASIA')], default=4),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email'),
        ),
    ]
