# Generated by Django 5.0.2 on 2024-10-08 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.IntegerField(choices=[(1, 'VIP'), (2, 'Exhibitor'), (3, 'Visitor')], default=3),
        ),
    ]
