# Generated by Django 5.1.5 on 2025-04-09 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_feedback_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='expo',
        ),
    ]
