# Generated by Django 5.1.5 on 2025-04-09 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_member_expo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='company',
            field=models.CharField(max_length=200, verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='member',
            name='position',
            field=models.CharField(choices=[('DIR', 'Директор'), ('DDIR', 'Заместитель директора'), ('HOD', 'Начальник отдела'), ('MGR', 'Менеджер'), ('SSP', 'Ведущий специалист'), ('SPC', 'Специалист'), ('INT', 'Стажер'), ('STD', 'Студент'), ('OTH', 'Другое')], default='OTH', max_length=4, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='member',
            name='registration_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время регистрации'),
        ),
    ]
