# Generated by Django 5.1.5 on 2025-04-09 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_member_company_alter_member_phone_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bank',
            new_name='Company',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='bank',
            new_name='company',
        ),
        migrations.AlterField(
            model_name='member',
            name='registration_time',
            field=models.TimeField(auto_now_add=True, verbose_name='Дата регистрации'),
        ),
    ]
