# Generated by Django 5.0.2 on 2024-09-09 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_member_qr_code_alter_ticket_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='member',
            name='qr_code',
            field=models.ImageField(default=1, upload_to='qr_codes/members/'),
            preserve_default=False,
        ),
    ]
