# Generated by Django 5.1.5 on 2025-04-09 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_bank_company_rename_bank_feedback_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='member',
            name='position',
            field=models.CharField(choices=[('DIR', 'Директор'), ('DDIR', 'Заместитель директора'), ('HOD', 'Начальник отдела'), ('MGR', 'Менеджер'), ('SSP', 'Ведущий специалист'), ('SPC', 'Специалист'), ('JSP', 'Младший специалист'), ('INT', 'Стажер'), ('STD', 'Студент'), ('OTH', 'Другое')], default='OTH', max_length=4, verbose_name='Должность'),
        ),
    ]
