# Generated by Django 5.0.2 on 2024-10-03 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_member_last_name_alter_member_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={},
        ),
        migrations.RenameField(
            model_name='member',
            old_name='first_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='member',
            name='role',
            field=models.IntegerField(choices=[(1, 'VIP'), (2, 'Exhibitor'), (3, 'Visitor')], default=3),
        ),
        migrations.AlterField(
            model_name='member',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/members/'),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_body', models.TextField()),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='api.member')),
            ],
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
