# Generated by Django 5.1.5 on 2025-04-10 18:43

import django.db.models.deletion
from django.db import migrations, models

def migrate_positions_forward(apps, schema_editor):
    Member = apps.get_model('api', 'Member')
    Position = apps.get_model('api', 'Position')
    
    # Create Position objects for each POSITION_CHOICES
    positions = {
        'DIR': Position.objects.create(name='Директор', code='DIR'),
        'DDIR': Position.objects.create(name='Заместитель директора', code='DDIR'),
        'HOD': Position.objects.create(name='Начальник отдела', code='HOD'),
        'MGR': Position.objects.create(name='Менеджер', code='MGR'),
        'SSP': Position.objects.create(name='Ведущий специалист', code='SSP'),
        'SPC': Position.objects.create(name='Специалист', code='SPC'),
        'JSP': Position.objects.create(name='Младший специалист', code='JSP'),
        'INT': Position.objects.create(name='Стажер', code='INT'),
        'STD': Position.objects.create(name='Студент', code='STD'),
        'OTH': Position.objects.create(name='Другое', code='OTH'),
    }
    
    # Update all existing members
    for member in Member.objects.all():
        old_position = member.position_old
        if old_position in positions:
            member.position = positions[old_position]
            member.save()

def migrate_positions_backward(apps, schema_editor):
    Position = apps.get_model('api', 'Position')
    Position.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_member_company_alter_member_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название должности')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код должности')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
                'ordering': ['name'],
            },
        ),
        migrations.RenameField(
            model_name='member',
            old_name='position',
            new_name='position_old',
        ),
        migrations.AddField(
            model_name='member',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.position', verbose_name='Должность'),
        ),
        migrations.RunPython(migrate_positions_forward, migrate_positions_backward),
        migrations.AlterField(
            model_name='member',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.position', verbose_name='Должность'),
        ),
        migrations.RemoveField(
            model_name='member',
            name='position_old',
        ),
    ]
