# Generated by Django 5.0.2 on 2024-10-07 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_member_options_rename_first_name_member_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='audio_feedback',
            field=models.FileField(blank=True, null=True, upload_to='audio_feedbacks/'),
        ),
    ]
